[package]
name = "blake3_optimized"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
rand = "0.10.0"
thiserror = "2.0.18"
tracing = { version = "0.1.44", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"], optional = true }
memmap2 = "0.9.11"

[features]
default = []
enable_tracing = ["dep:tracing", "dep:tracing-subscriber"]

[profile.release]
debug = 2

[dev-dependencies]
criterion = "0.7"
rand = "0.10.0"
blake3 = "1"

[[bench]]
name = "compress"
harness = false
